'use strict';
const assert = require('node:assert/strict');
const store = require('../lib/store');
store.useMemoryDriver();
store.hydrate({});
const { execute, handleMcp } = require('../lib/mcp');
const { handleApi } = require('../lib/api');
const user = { id: 'test', email: 'mcp@example.test', budget: { monthlyCap: 200, spent: 0, cycleStart: Date.now() } };
store.putUser(user);
const options = execute(user, 'find_gifts', { category: 'flowers', max_amount: 100 });
assert(options.options.length > 0);
const order = execute(user, 'prepare_gift_order', { product: options.options[0].name, recipient: 'Maya', card_message: 'Happy birthday!' });
assert.equal(user.budget.spent, 0);
assert.throws(() => execute(user, 'approve_gift_order', { order_id: order.id, approved_total: order.total, user_approved: false }));
assert.throws(() => execute(user, 'approve_gift_order', { order_id: order.id, approved_total: order.total + 1, user_approved: true }));
assert.throws(() => execute({ id: 'other' }, 'get_order_status', { order_id: order.id }));
const approval = { order_id: order.id, approved_total: order.total, user_approved: true };
execute(user, 'approve_gift_order', approval);
execute(user, 'approve_gift_order', approval);
assert.equal(user.budget.spent, order.total);
assert.equal(order.status, 'simulated — approved');
const next = execute(user, 'prepare_gift_order', { product: options.options[0].name, recipient: 'Maya', card_message: 'Cheers' });
user.budget.monthlyCap = user.budget.spent;
assert.throws(() => execute(user, 'approve_gift_order', { order_id: next.id, approved_total: next.total, user_approved: true }));
assert.equal(next.status, 'awaiting approval');
next.expires_at = 0;
assert.throws(() => execute(user, 'approve_gift_order', { order_id: next.id, approved_total: next.total, user_approved: true }));
assert.equal(handleMcp(user, { method: 'POST', body: { jsonrpc: '2.0', id: 1, method: 'tools/list' } }).json.result.tools.length, 5);
handleApi({ method: 'POST', pathname: '/api/mcp', body: {} }).then(result => {
  assert.equal(result.status, 401);
  console.log('MCP approval, isolation, idempotency, budget, expiry and auth checks passed');
}).catch(e => { console.error(e); process.exitCode = 1; });
