'use strict';
const assert = require('node:assert/strict');
const crypto = require('crypto');
const store = require('../lib/store');
store.useMemoryDriver(); store.hydrate({});
const oauth = require('../lib/oauth');
const { handleApi } = require('../lib/api');
(async () => {
  const user={id:'oauth-user',email:'oauth@example.test',budget:{monthlyCap:150,spent:0,cycleStart:Date.now()}};
  store.putUser(user);
  const c=await oauth.register({client_name:'Test assistant',redirect_uris:['https://chatgpt.com/test-callback'],token_endpoint_auth_method:'none'});
  const verifier=crypto.randomBytes(32).toString('base64url');
  const args={client_id:c.client_id,redirect_uri:c.redirect_uris[0],response_type:'code',resource:oauth.RESOURCE,scope:'gifts:simulate',state:'test-state',code_challenge:crypto.createHash('sha256').update(verifier).digest('base64url'),code_challenge_method:'S256',approve:true};
  await assert.rejects(oauth.authorize(user,{...args,redirect_uri:'https://attacker.example/callback'}));
  await assert.rejects(oauth.authorize(user,{...args,approve:false}));
  await assert.rejects(oauth.authorize(user,{...args,resource:'https://other.example/mcp'}));
  const redirect=new URL((await oauth.authorize(user,args)).redirect);
  assert.equal(redirect.searchParams.get('state'),'test-state');
  const exchange={grant_type:'authorization_code',client_id:c.client_id,redirect_uri:c.redirect_uris[0],resource:oauth.RESOURCE,code:redirect.searchParams.get('code'),code_verifier:verifier};
  await assert.rejects(oauth.exchange({...exchange,code_verifier:'bad'},{}));
  const tokens=await oauth.exchange(exchange,{});
  await assert.rejects(oauth.exchange(exchange,{}));
  assert.equal((await oauth.tokenUser(tokens.access_token)).id,user.id);
  const headers={authorization:'Bearer '+tokens.access_token};
  assert.equal((await handleApi({method:'POST',pathname:'/api/budget',headers,body:{monthlyCap:1000}})).status,401);
  const result=await handleApi({method:'POST',pathname:'/api/mcp',headers,body:{jsonrpc:'2.0',id:1,method:'tools/call',params:{name:'get_budget',arguments:{}}}});
  assert.equal(result.json.result.structuredContent.monthlyCap,150);
  const refresh={grant_type:'refresh_token',client_id:c.client_id,resource:oauth.RESOURCE,refresh_token:tokens.refresh_token};
  await oauth.exchange(refresh,{}); await assert.rejects(oauth.exchange(refresh,{}));
  await oauth.route({pathname:'/api/oauth/revoke',method:'POST',body:{client_id:c.client_id,token:tokens.access_token},headers:{}},null);
  assert.equal(await oauth.tokenUser(tokens.access_token),null);
  assert((await handleApi({pathname:'/api/mcp',method:'POST',headers:{},body:{}})).headers['WWW-Authenticate']);
  console.log('OAuth checks passed: PKCE, consent, redirect/resource binding, one-use grants, refresh rotation, revocation and MCP-only access.');
})().catch(e=>{console.error(e);process.exitCode=1;});
