'use strict';
const assert = require('node:assert/strict');
const store = require('../lib/store');
const catalog = require('../lib/catalog');
const { execute } = require('../lib/mcp');
store.useMemoryDriver(); store.hydrate({});
const user = { id: 'search', email: 'search@example.test', budget: { monthlyCap: 140, spent: 130, cycleStart: Date.now() } };
store.putUser(user);
const result = execute(user, 'find_gifts', { max_amount: 60 });
assert.equal(result.options.length, catalog.filter(p => p.price <= 60).length);
assert(result.options.length > 0);
assert(result.options.every(p => p.price <= 60 && p.image_url));
assert(result.options.some(p => !p.within_budget && p.budget_shortfall === p.price - 10));
assert.equal(result.remaining_budget, 10);
assert.equal(user.budget.spent, 130);
const categories = execute(user, 'list_gift_categories', {}).valid_categories;
assert(categories.includes('food') && !categories.includes('birthday'));
assert.deepEqual(result.valid_categories, categories);
const birthday = execute(user, 'find_gifts', { category: 'Birthday', max_amount: 60 });
assert.equal(birthday.occasion, 'birthday');
assert.equal(birthday.category, null);
assert.equal(birthday.options.length, result.options.length);
assert.match(birthday.occasion_note, /no occasion-specific tags/);
const foodBirthday = execute(user, 'find_gifts', { category: ' FOOD ', occasion: 'birthday', max_amount: 60 });
assert(foodBirthday.options.length > 0 && foodBirthday.options.every(p => p.category === 'food'));
const invalid = execute(user, 'find_gifts', { category: 'books', max_amount: 60 });
assert.equal(invalid.invalid_category, 'books');
assert.equal(invalid.options.length, 0);
assert.deepEqual(invalid.valid_categories, categories);
assert.match(invalid.message, /Valid categories:/);
const none = execute(user, 'find_gifts', { max_amount: 1 });
assert.equal(none.options.length, 0);
assert.match(none.message, /maximum amount/);
const p = result.options.find(p => !p.within_budget);
const order = execute(user, 'prepare_gift_order', { product: p.name, recipient: 'Josh', card_message: 'Happy birthday' });
assert.throws(() => execute(user, 'approve_gift_order', { order_id: order.id, approved_total: order.total, user_approved: true }), /over budget/);
assert.equal(user.budget.spent, 130);
assert.equal(store.listGifts(user.id).length, 0);
console.log('Catalog browsing, affordability, occasions, category guidance and approval budget checks passed');
