// Auto-generated from the live store catalog. The gift the agent picks is drawn from these.
module.exports = [
  { name: "Seasonal local flower bouquet", price: 65, category: "flowers" },
  { name: "Wildflower & eucalyptus arrangement", price: 85, category: "flowers" },
  { name: "Long-lasting potted orchid", price: 70, category: "flowers" },
  { name: "Dried flower keepsake bouquet", price: 55, category: "flowers" },
  { name: "Peony & garden rose arrangement", price: 95, category: "flowers" },
  { name: "Sterling silver pendant", price: 140, category: "jewelry" },
  { name: "Fine gold-plated bracelet", price: 210, category: "jewelry" },
  { name: "Stacked hoop earrings", price: 90, category: "jewelry" },
  { name: "Engraved cufflinks", price: 85, category: "jewelry" },
  { name: "Minimalist leather-strap watch", price: 180, category: "jewelry" },
  { name: "Smart fitness tracker", price: 130, category: "tech" },
  { name: "Wireless noise-cancelling earbuds", price: 150, category: "tech" },
  { name: "Smart hydration water bottle", price: 45, category: "tech" },
  { name: "Portable espresso maker", price: 65, category: "tech" },
  { name: "Smart digital photo frame", price: 110, category: "tech" },
  { name: "Signature fragrance, 50ml", price: 120, category: "grooming" },
  { name: "Premium grooming kit", price: 75, category: "grooming" },
  { name: "Luxury wet-shave set", price: 60, category: "grooming" },
  { name: "Skincare essentials gift set", price: 95, category: "grooming" },
  { name: "Cologne & aftershave duo", price: 85, category: "grooming" },
  { name: "Hand-forged USA chef's knife", price: 120, category: "handmade" },
  { name: "Engraved leather journal", price: 55, category: "handmade" },
  { name: "Custom name leather wallet", price: 70, category: "handmade" },
  { name: "Hand-thrown ceramic mug set", price: 48, category: "handmade" },
  { name: "Personalized engraved cutting board", price: 65, category: "handmade" },
  { name: "Plush oversized throw blanket", price: 60, category: "home" },
  { name: "Scented candle trio", price: 50, category: "home" },
  { name: "Memory foam pillow", price: 80, category: "home" },
  { name: "Cozy loungewear pajama set", price: 65, category: "home" },
  { name: "Smart bedside reading lamp", price: 75, category: "home" },
  { name: "At-home spa gift box", price: 90, category: "wellness" },
  { name: "Weighted comfort blanket", price: 95, category: "wellness" },
  { name: "Aromatherapy diffuser set", price: 55, category: "wellness" },
  { name: "Yoga mat & accessories bundle", price: 70, category: "wellness" },
  { name: "Sleep mist & pillow spray set", price: 40, category: "wellness" },
  { name: "Sunset beach bike rental, for two", price: 90, category: "experiences" },
  { name: "Guided day hike for two", price: 110, category: "experiences" },
  { name: "Weekend camping essentials kit", price: 85, category: "experiences" },
  { name: "Rooftop dinner reservation", price: 150, category: "experiences" },
  { name: "Private golf lesson package", price: 130, category: "experiences" },
  { name: "Cashmere scarf", price: 95, category: "fashion" },
  { name: "Leather weekend duffel bag", price: 190, category: "fashion" },
  { name: "Classic wool cap", price: 45, category: "fashion" },
  { name: "Silk pocket square set", price: 50, category: "fashion" },
  { name: "Statement designer sunglasses", price: 110, category: "fashion" },
  { name: "Artisan chocolate & wine pairing box", price: 75, category: "food" },
  { name: "Small-batch coffee subscription, 3mo", price: 60, category: "food" },
  { name: "Whiskey tasting flight box", price: 95, category: "food" },
  { name: "Gourmet cheese & charcuterie box", price: 70, category: "food" },
  { name: "Specialty loose-leaf tea sampler", price: 40, category: "food" },
];


// These existing hosted catalog assets are illustrative prototype product photos.
module.exports.forEach((p, index) => {
  p.image_url = `https://papaya-cassata-7e507b.netlify.app/assets/products/p${index}.jpg`;
  p.image_alt = p.name + " (illustrative catalog photo)";
});
